# Generated by Django 5.1.6 on 2025-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0004_alter_titles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='hls_video',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
